import os
from dotenv import load_dotenv

load_dotenv()
from typing import List
from pydantic import BaseModel, Field
from langchain.agents import create_agent
from langchain.agents.structured_output import ToolStrategy
from langchain.tools import tool
from langchain.messages import HumanMessage
from langchain_ollama import ChatOllama
from langchain_tavily import TavilySearch
from langsmith import traceable

class Source(BaseModel):
    """
    This class represents and stores URL of each Source.
    """
    url:str = Field(description="the source url from the agent response")

class AgentResponse(BaseModel):
    """
    Defines the Data type representation in which downstream processes are expecting Agent output
    answer: str = The raw response generated by the agent at the end.
    sources: list = list of Source objects that will be retrived from the agent response.
    """
    answer:str = Field(description="Last response of the Agent")
    sources:List[Source] = Field(
        default_factory=list, description="List of sources used to generate the answer"
    )


llm = ChatOllama(model="gpt-oss:20b", temperature=0)
tools = [TavilySearch()]
search_agent = create_agent(
    model=llm,
    tools=tools,
    response_format=ToolStrategy(AgentResponse),
    system_prompt="You are a search agent and you will use the search_tool to perform search on users query"
)

@traceable
def main():
    print("Hello from langchain-course!")
    response = search_agent.invoke({"messages":[HumanMessage(content="Latest and top 3 open jobs for Langchain AI Engineer on LinkedIn")]})
    print(response)

if __name__ == "__main__":
    main()
